# Generated by Django 6.0.3 on 2026-05-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_wordfilter_word_word_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='difficulty',
        ),
    ]
