# Generated by Django 6.0.3 on 2026-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_remove_word_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='practiced_once',
            field=models.BooleanField(default=False),
        ),
    ]
