LANGUAGE_ENGLISH = 'en'
LANGUAGE_RUSSIAN = 'ru'

SUPPORTED_LANGUAGES = [
    LANGUAGE_ENGLISH,
    LANGUAGE_RUSSIAN,
]

FILTER_ANY = 'any'
FILTER_NONE = 'none'

MAX_PRACTICE_QUESTIONS = 10
MIN_PRACTICE_WORDS = 3